remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Earl Matthews Github site
description: A collection of appllications I've written
author:
    name: Earl Matthews
    email: earl[dot]matthews[at]gmail.com
    github: EarlMatthews
    twitter: earlmatthews
production_url : https://earlmatthews.github.io/myrepo
BASE_PATH : https://earlmatthews.github.io/myrepo
markdown : kramdown